name: Draft Release Windows

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Install SignPath module
        run: Install-Module -Name SignPath -Force
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.pat }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: yarn install --network-timeout 600000 && yarn allow-scripts

      - name: Build artifacts.
        run: yarn dist:win

      - name: Create signed folder
        run: mkdir signed

      - name: Upload build file to Signpath
        run: Submit-SigningRequest `
          -InputArtifactPath "dist/HyperPlay*.exe" `
          -CIUserToken  ${{ secrets.SIGNPATH_TOKEN }}`
          -OrganizationId ${{ secrets.SIGNPATH_ORG_ID }} `
          -ProjectSlug "HyperPlay_Win_x64" `
          -SigningPolicySlug "Release_Signing" `
          -OutputArtifactPath "signed" `
          -WaitForCompletion

      - name: Update latest.yml
        run: |
          $artifactPath = Get-ChildItem -Path signed -Filter HyperPlay*.exe
          $sha512 = Get-FileHash -Path $artifactPath -Algorithm SHA512 | Select-Object -ExpandProperty Hash
          $size = (Get-Item $artifactPath).Length
          $latestYml = Get-Content -Path build/latest.yml -Raw | ConvertFrom-Yaml
          $latestYml.files[0].sha512 = $sha512
          $latestYml.files[0].size = $size
          $latestYml | ConvertTo-Yaml -Depth 100 | Set-Content -Path signed\latest.yml

      - name: Create draft release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: signed\HyperPlay*.exe
          asset_name: HyperPlay*.exe
          asset_content_type: application/octet-stream

      - name: Upload release asset
        id: upload-latest-yml
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: signed\latest.yml
          asset_name: latest.yml
          asset_content_type: application/octet-stream
