name: Draft Release Windows

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Install SignPath module
        run: Install-Module -Name SignPath -Force
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.pat }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: yarn setup

      - name: Build artifacts.
        run: yarn dist:win
        env:
          NOTARIZE: true
      - name: Upload build file to Signpath
        run: Submit-SigningRequest -InputArtifactPath dist/HyperPlay*.exe -ProjectSlug HyperPlay_Win_x64 -SigningPolicySlug Release_Signing -ArtifactConfigurationSlug initial -OrganizationId ${{secrets.SIGNPATH_ORG_ID}} -CIUserToken ${{ secrets.SIGNPATH_TOKEN }}
